package ca.mcgill.ecse321.PLMS.model;

import jakarta.persistence.*;

/**
 * Class that is part of the domain model of the Parking Lot Management System (PLMS)
 * This class contains information that is unique to employee accounts
 * 
 * A major part of this class is auto-generated by umple
 * This class is also JPA anotated for ORM
 */
@Entity
public class Employee extends Account
{

  //------------------------
  // MEMBER VARIABLES
  //------------------------

  //Employee Attributes
  private String jobTitle;
  private double hourlyWage;

  

  //------------------------
  // INTERFACE CONSISTING OF GETTERS AND SETTERS
  //------------------------

  public boolean setJobDescription(String aJobTitle)
  {
    boolean wasSet = false;
    jobTitle = aJobTitle;
    wasSet = true;
    return wasSet;
  }

  public boolean setHourlyWage(int aHourlyWage)
  {
    boolean wasSet = false;
    hourlyWage = aHourlyWage;
    wasSet = true;
    return wasSet;
  }

  public String getJobTitle()
  {
    return jobTitle;
  }

  public double getHourlyWage()
  {
    return hourlyWage;
  }

 /**
 * toString() helper method
 * Helpful for debugging
 */
  public String toString()
  {
    return super.toString() + "["+
            "jobTitle" + ":" + getJobTitle()+ "," +
            "hourlyWage" + ":" + getHourlyWage()+ "]";
  }
}