package ca.mcgill.ecse321.PLMS.model;

import jakarta.persistence.*;

/**
 * Class that is part of the domain model of the Parking Lot Management System (PLMS)
 * This class represents a the owner's account
 * 
 * A major part of this class is auto-generated by umple
 * This class is also JPA anotated for ORM
 */
@Entity
public class Owner extends Account
{

  //------------------------
  // MEMBER VARIABLES (all belong to the super class account)
  //------------------------

  /**
   * Constructor of owner class invokes super class constructor
   * @param aEmail - email of the owner
   * @param aPassword - password of the owner
   * @param aName - name of the owner
   */
  public Owner(String aEmail, String aPassword, String aName)
  {
    super(aEmail, aPassword, aName);
  }



}